linters-settings:
  depguard:
    list-type: blacklist
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  importas:
    no-unaliased: true
    alias:
      # cover vcluster-sdk
      - pkg: github.com/loft-sh/vcluster-sdk/(\w+)
        alias: vclustersdk$1
      - pkg: github.com/loft-sh/vcluster-sdk/(\w+)/(\w+)
        alias: vclustersdk$1$2
      # controller-runtime
      - pkg: sigs.k8s.io/controller-runtime
        alias: ctrlruntime
      # controller-runtime-client
      - pkg: sigs.k8s.io/controller-runtime/pkg/client
        alias: ctrlruntimeclient
      # cover apimachinery packages ex: metav1
      - pkg: k8s.io/apimachinery/pkg/apis/(\w+)/(\w+)
        alias: $1$2
      # cover apimachinery errrors
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apimachineryerrors
  lll:
    line-length: 100
  stylecheck:
    checks:
      - "-ST1000"
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  revive:
    rules:
      - name: exported
linters:
  enable:
    - nlreturn
    - forbidigo
    - gofumpt
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - importas
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - goerr113
    - nestif
    - prealloc
    - testpackage
    - wsl

issues:
  # https://github.com/golangci/golangci-lint/issues/2439#issuecomment-1002912465
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl
        - structcheck
        - unused
        - unparam
        - funlen

run:
  go: '1.19'
  skip-dirs:
    - .private
    - vendor

service:
  golangci-lint-version: 1.50.x
