---
apiVersion: v1
kind: ConfigMap
metadata:
  name: real-configmap
  namespace: vcluster
data:
  redis.conf: |
    somekey=somevalue
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: virtual-configmap
  namespace: vcluster
data:
  redis.conf: |
    virtualkey=virtualvalue