---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: vcluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
# skip annotations need to be directly on the pod/pod tempalte
#      annotations:
#        skip-prefer-parent-configmaps-hook: "true"
#        skip-prefer-parent-secrets-hook: "true"
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          volumeMounts:
            - name: secret
              mountPath: /dummy
          env:
            - name: SECRET_STUFF
              valueFrom:
                secretKeyRef:
                  name: real-secret
                  key: super-secret-secret
                  optional: false
      volumes:
        - name: secret
          secret:
            secretName: real-secret
